spring.application.name=fleetGpsTracking
spring.datasource.url=jdbc:postgresql://127.0.0.1/fleet_gps_track
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true 
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
gps.logs.cleanup.days=30
jwt.secret=qElBTL7sXaDfQ5WWJD+MWLg7TuY0ke5Y23S4oeBPefA=
jwt.expired_time=86400000